// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/victorfong/twitter-auto/model (interfaces: Database)

package mock

import (
	// sql "database/sql"
	gomock "github.com/golang/mock/gomock"
	// . "github.com/victorfong/twitter-auto/model"
)

// Mock of Database interface
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *_MockDatabaseRecorder
}

// Recorder for MockDatabase (not exported)
type _MockDatabaseRecorder struct {
	mock *MockDatabase
}

func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &_MockDatabaseRecorder{mock}
	return mock
}

func (_m *MockDatabase) EXPECT() *_MockDatabaseRecorder {
	return _m.recorder
}

func (_m *MockDatabase) SyncFollowers(ids []int64) error {
	ret := _m.ctrl.Call(_m, "SyncFollowers", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDatabaseRecorder) SyncFollowers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SyncFollowers", arg0)
}

func (_m *MockDatabase) SyncFollowings(id []int64) error {
	ret := _m.ctrl.Call(_m, "SyncFollowings", id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDatabaseRecorder) SyncFollowings(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SyncFollowings", arg0)
}

func (_m *MockDatabase) GetUnfollowList() ([]int64, error) {
	ret := _m.ctrl.Call(_m, "GetUnfollowList")
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDatabaseRecorder) GetUnfollowList() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetUnfollowList")
}

func (_m *MockDatabase) Unfollow(ids []int64) error {
	ret := _m.ctrl.Call(_m, "Unfollow", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDatabaseRecorder) Unfollow(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unfollow", arg0)
}
